### ISSUE TITLE
Why not use GLFW?

### ISSUE THREAD

**Issue by danomatika** [elliotwoods/ofxClipboard#1]
GLFW supports this already. [I'm using it in ofxGLEditor](https://github.com/Akira-Hayasaka/ofxGLEditor/blob/master/src/ofxEditor.cpp#L1330): 

```
// set clipboard
ofAppGLFWWindow *window = (ofAppGLFWWindow *) ofGetWindowPtr();
glfwSetClipboardString(window->getGLFWWindow(), text.c_str());

// get clipboard
ofAppGLFWWindow *window = (ofAppGLFWWindow *) ofGetWindowPtr();
const char * text = glfwGetClipboardString(window->getGLFWWindow());
```

Of course this only works on desktop where GLFW is being used, but I just use compile time checks to enable it.

**Comment by danomatika** [comment]
To be a completist:

As far as IOS goes, you can use [UIPasteboard](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIPasteboard_Class/index.html#//apple_ref/occ/clm/UIPasteboard/generalPasteboard), but that will involve a separate *.mm Obj-C++ file for it compile correctly.

For Android it looks like the [Clipboard Manager](https://developer.android.com/guide/topics/text/copy-paste.html).

I talked with Chris about the clipboard on the RaspberryPI and there really isn't a terminal wide copy & paste buffer, so I'm just using an internal in-app buffer.

**Comment by elliotwoods** [comment]
hey Dan. good to hear from you!

and good spot with glfw
so that would work for Linux too.

if somebody PR's other platforms (like mobile) then i'm definitely for adding them.

also your suggestion of an app-wide clipboard for unsupported platforms makes total sense.

the priority for me currently is to have an interface to work with, and add platforms as they're required/available/added by others. I'm just surprised this doesn't exist already.

**Comment by elliotwoods** [comment]
any issues with some people still not using GLFW?

**Comment by danomatika** [comment]
Maybe some people still use GLUT manually, but most people are using OF with the default window manager which has been GLFW for the last few releases at least. I just mainly suggest using existing implementations in frameworks like GLFW instead of having to roll your own platform specific stuff.

**Comment by elliotwoods** [comment]
totally agree
